eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: appDemo1
          uri: http://localhost:8556
          predicates:
            - Path=/appDemo_1/send
        - id: appDemo2
          uri: http://localhost:8557
          predicates:
            - Path=/appDemo_2/send
        - id: appDemo3
          uri: http://localhost:8558
          predicates:
            - Path=/appDemo_3/**
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
        - id: messages
          uri: http://localhost:8091
          predicates:
            - Path=/messages/**
        - id: transformation
          uri: http://localhost:8092
          predicates:
            - Path=/api/messages/**
